### ISSUE TITLE
【overflowX、Y】关闭了纵向滚动还是可以看到 竖滚动条

### ISSUE THREAD

**Issue by ShenQingchuan** [any86/any-scroll#2]
# 问题描述

我本来是想试着用 any-scroll 做一个 Tab 组件的 标题头的，想让有多个 Tab title 的时候 能滚动起来，但是看到滚动时仍然有竖直滚动条

就是如果我在 any-scroll 组件的范围内鼠标有上下的运动 ，还是会显示 右边的竖向滚动条，这不好，不是我想要的效果。

![image](https://user-images.githubusercontent.com/46062972/66918198-63451600-f051-11e9-9435-23bbb6952403.png)

（我的 any-scroll中是一个 横向的 ul li ）

因为我看到您的官方文档中 关闭了 横向滚动后，我即使上下拖动，也不会出现竖向滚动条

![image](https://user-images.githubusercontent.com/46062972/66919331-b8822700-f053-11e9-8cdd-221a2872d7a3.png)

# 使用时的代码部分：

```vue

<any-scroll :overflowX="false" :overflowY="true" width="90vw" height="38px" >
      <ul class="tab-title-container">
        <li
          v-for="(title,index) in titles"
          :key="index"
        >
            {{title}}
        </li>
      </ul>
    </any-scroll>

```

# 希望效果

竖直方向没有滚动条。

**Comment by any86** [comment]
好的，感谢反馈，我看下代码改下🚀

**Comment by ShenQingchuan** [comment]
另外您 代码仓库中的 App.vue 中 使用的 Prop 是 `:overflow-x="(一个变量)"`  经我测试 这个 prop 并不能用... 检查了您 `/src/components/ScrollBar.vue` 中定义的属性也还是 `overflowX 和 overflowY` 没有中横线，不知道是怎么回事😂

**Comment by any86** [comment]
@ShenQingchuan 我的毛病, 我改下, ⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by any86** [comment]
![image](https://user-images.githubusercontent.com/8264787/66929302-5f22f380-f065-11e9-818a-d530bca9ce30.png)

**Comment by any86** [comment]
鼠标的问题, 我没复现出来, 能说下如何复现的吗?

我更新了any-scroll依赖的any-touch(我最近一直在迭代any-touch), 不知道更新后还会不会有你说的鼠标的bug, 有问题告诉我😂

**Comment by any86** [comment]
> 另外您 代码仓库中的 App.vue 中 使用的 Prop 是 `:overflow-x="(一个变量)"` 经我测试 这个 prop 并不能用... 检查了您 `/src/components/ScrollBar.vue` 中定义的属性也还是 `overflowX 和 overflowY` 没有中横线，不知道是怎么回事😂
这个是vue的特性，2者是等价的

**Comment by ShenQingchuan** [comment]
# 一个Awesome的修复！感谢大大！
非常感谢您做出的贡献！

# 其他问题：
不过我还有一个不情之请，就是我刚才在 any-scroll 测试移动端表现时遇到如下问题：

1. 在您的 展示页面中： 我切换到移动端 iphone 6/7/8Plus 测试发现，提交按钮的点击事件并未被屏蔽
2. 但在我的代码中：
![image](https://user-images.githubusercontent.com/46062972/66968464-df724480-f0b7-11e9-8bb0-596061eb1549.png)

不知道这个是不是我的问题o(╥﹏╥)o，因为我在 PC 模式下的确表现良好。

**Comment by ShenQingchuan** [comment]
刚刚以 iPhone 6/7/8 Plus 状态下刷新页面访问您给出的展示页面，那个提交按钮的点击事件也应该是被 any-scroll 层屏蔽了...

这个问题似乎很难解决...😂

我看到您展示页面中，有在描述 **滚动状态**，我在想如果是 x，y 轴向都为 `static`，（即该时刻any-scroll区域不动）,  是否可以在这个状态下修改呢~？

**Comment by any86** [comment]
不是你的问题, 我稍微修改下,一会暴露出一个参数就能解决

**Comment by any86** [comment]
请问是在真实手机上访问的? 还是谷歌模拟器? 和滚动应该没关系, 我猜测可能是我默认加的css的touch-action引起的, 我测试下做下修改

**Comment by ShenQingchuan** [comment]
> 请问是在真实手机上访问的? 还是谷歌模拟器? 和滚动应该没关系, 我猜测可能是我默认加的css的touch-action引起的, 我测试下做下修改

是谷歌的模拟器，真机还没做测试，我现在上课了...  ToT

**Comment by any86** [comment]
# any-scroll 升级到0.0.4
暂时解决了这个问题, 但不是终极方案. 稍后0.0.5中我会加一个参数(正则)对指定的元素进行"阻止默认事件"而不是全部.
0.0.5的时候直接升级下就好了, 不会更改现有api

**Comment by ShenQingchuan** [comment]
> # any-scroll 升级到0.0.4
> 暂时解决了这个问题, 但不是终极方案. 稍后0.0.5中我会加一个参数(正则)对指定的元素进行"阻止默认事件"而不是全部.
> 0.0.5的时候直接升级下就好了, 不会更改现有api

万分感谢您！

**Comment by any86** [comment]
客气客气啦

**Comment by ShenQingchuan** [comment]
🤣实在抱歉打扰，另外还有一个问题，就是 **关于 VuePress 开发的文档中、运用到任何使用了any-scroll的组件时，在打包过程中会报错**

但考虑到起始对本组件本身意义不大，我只在这里提一下：

就是我在使用 VuePress 打包的时候，本来在 VuePress 的开发模式下，是可以正常显示的，但是打包的时候却提示  window is undefined... 还有类似 document is undefined 等等...

![image](https://user-images.githubusercontent.com/46062972/66988968-064f6b80-f0f6-11e9-87a9-6f2518f45025.png)

索引的具体位置是这里：

![image](https://user-images.githubusercontent.com/46062972/66988997-18c9a500-f0f6-11e9-93e4-fb98ead0477a.png)

（IS_WX看上去像是判断 微信小程序平台的...）

**Comment by any86** [comment]
这个我之前还真没试过, vuepress生成的页面是支持ssr的吧? 估计我需要对win和doc这2全局对象做为空判断, 稍后我结合vuepress做下修改

**Comment by ShenQingchuan** [comment]
好的，我也再看看呐~

**Comment by any86** [comment]
vuepress好像有不适用ssr(服务端渲染)的开关, 不行暂时把他关了, 应该可以规避这个问题(暂时方法)

**Comment by ShenQingchuan** [comment]
> vuepress好像有ssr(服务端渲染)的开关, 不行暂时把他关了, 应该可以规避这个问题(暂时方法)

没错，我尝试了按照 VuePress 官网的写法，动态引入 any-scroll

```vue
<component v-if="AnyScroll" :is="AnyScroll" 
      style="width: inherit;"
      :overflowX="false" :overflowY="true" 
      :isShowXBar="false" :isShowYBar="false"
      width="90vw" height="40px" bounceDistance="0">
</component>

<script>
export default {
    ....
    data() {
         // dynamicComponents: 
        AnyScroll: null,
    },
    mounted() {
        import('any-scroll').then(mod => {
          // use code
          this.AnyScroll = mod.default;
    })
}
</script>

```


## 最终结果成功！
![image](https://user-images.githubusercontent.com/46062972/66998128-49193f80-f106-11e9-9507-11581f9912fa.png)

```bash

√ Client
  Compiled successfully in 12.92s

√ Server
  Compiled successfully in 5.59s

wait Rendering static HTML...
success Generated static files in src\docs\.vuepress\dist.

Done in 15.54s.
```

**Comment by any86** [comment]
厉害!  恭喜!  和你学了一招, 嘿嘿.

**Comment by any86** [comment]
看了你的项目,已star.  遇到什么需要帮忙的随时留言. :rocket:

**Comment by ShenQingchuan** [comment]
> 看了你的项目,已star. 遇到什么需要帮忙的欢迎随时留言. 🚀

哇太感谢您了！从您的项目中学到很多！

**Comment by any86** [comment]
太客气了，互相学习，你的UI界面和别人的风格不太一样，挺有卖点的，加油
